### ISSUE TITLE
3.0 Update?

### ISSUE THREAD

**Issue by Bannyfelt13** [Sorapointa/MagicSniffer#1]
如题

**Comment by Konoyoru435** [comment]
马上呜呜呜

**Comment by Konoyoru435** [comment]
`WindSeedClientNotify` 被神笔了（悲

**Comment by WetABQ** [comment]
WindSeed 被删掉了，现在用不了，我们在考虑先用一个假客户端进入服务器获取一些相对固定包（对于每个帐号而言的相对固定），然后借此进行和先前同样的操作。

----

MagicSniffer doesn't work due to `WindSeedClientNotify` seems to be rm by mhy.
But it does not mean we can't sniff it in the same way, there are several ways to get unique plainText for each account (and constant for a while), such as AvatarDataNotify or QuestBlablabla, we could get those of plainText by a dummy client (so it could exchange real RSA key with official server).

We are still working on those new ways but it might need we take a long time to update.

**Comment by WetABQ** [comment]
WindSeed came back
